### ISSUE TITLE
git dependencies generate linting errors

### ISSUE THREAD

**Issue by shawninder** [kilian-ito/atom-npm-outdated#2]
## Reproduction steps

1. Make a package.json with a git dependency, e.g. `"lodash": "git+https://github.com/lodash/lodash.git"`
2. EXPECT no linting errors or warnings
3. OBSERVE a linting _error_ saying "The package lodash has an invalid range version"

## Another manifestation

In my case, I am referring to a private git repo, like this: `"my-package": "git+https://TOKEN:x-oauth-basic@github.com/OWNER/REPO.git#BRANCH"`. This time the linting _error_ I get is `The package my-package is not found on https://registry.npmjs.org`

**Comment by kilian-ito** [comment]
Hi @shawninder,

Thank you for the report.
The package was only supporting the dependencies with range version (following semserv notation).

I have fixed this issue by ignoring the dependencies targeting local files and URLs (based on the list of supported dependency specifications on https://docs.npmjs.com/files/package.json#dependencies).

Regards.

**Comment by shawninder** [comment]
I am still seeing a linting error with the following dependency:
```
"my-super-awesome-package": "git+https://MY_OAUTH_TOKEN:x-oauth-basic@github.com/OWNER/REPO.git#BRANCH",
```

using atom-npm-outdated 0.13.1.

This is pretty surprising since both this censored version (the code from above) and the real (from my actual source code) both match the regexp responsible for ignoring this dependency (i.e. `/^git(\+(ssh|https?|file):\/\/)?.*/ig`, from https://github.com/kilian-ito/atom-npm-outdated/commit/dffeb8b0a40e82e57d6ce90266f0c2c81c09a259#diff-98bf811b7b68f5089bfb2605df5b2548R55). Any idea what is going on here?

**Comment by shawninder** [comment]
If it helps, I have configured atom-npm-outdated with the following settings:
Check installed package version: true
Display information: true
NPM package inromation base url: DEFAULT
Path to NPM config file: DEFAULT
Level or prerelease: stable

**Comment by kilian-ito** [comment]
The issue has been fixed in the version 13.2.
If a valid http/git/ssh url is specified the validation of the package is ignored.
